name: "Send CI errors to slack channel"
author: GDS
description: "Send CI errors to a nominated slack channel"
inputs:
  test-name:
    description: "Name of the test to check for CI failures"
    required: true
    default: "Run Minitest"
runs:
  using: node20
  main: check_errors.js