name: Run Minitest
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-minitest:
    name: Run Minitest
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Simulate failure
        id: run_test
        env:
          JOB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$JOB_CONTEXT" 
          echo "Error always failing"
          exit 1
      - if: ${{ failure() }}
        uses: ./.github/actions/send_ci_errors
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          channel: test-ci
          github: ${{ toJson(github) }}
