name: Run Minitest
on:
  workflow_dispatch:

jobs:
  run-minitest:
    name: Run Minitest
    runs-on: ubuntu-22.04

    steps:
        - uses: actions/checkout@v4
        - name: Simulate failure
          id: run_test
          # continue-on-error: true
          run: | 
            echo "Error always failing"
            exit 1
        - uses: ./.github/actions/check_errors
  