name: Run Minitest
on:
  workflow_dispatch:

jobs:
  run-minitest:
    name: Run Minitest
    runs-on: ubuntu-22.04
    steps:
        - uses: actions/checkout@v4
        - uses: ./.github/actions/check_errors
        - name: Simulate failure
          run: echo "Error always failing"
  